export const DEFAULT_SIGNIN_REDIRECT = "/"
export const DEFAULT_SIGNOUT_REDIRECT = "/"
export const DEFAULT_UNAUTHENTICATED_REDIRECT = "/signin"
export const DEFAULT_AUTHENTICATED_REDIRECT = "/new-account"
export const DEFAULT_REDIRECT_TO_STUDENT_DASHBOARD = "/student/dashboard"
export const DEFAULT_REDIRECT_TO_INSTITUTION_DASHBOARD = "/institution/dashboard"
export const DEFAULT_REDIRECT_TO_ORDER_PROCESS="/institution/order-process/"
